
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/sonarr-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/sonarr/data:/data
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/TV:/tv
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/radarr-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/radarr/data:/data
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Movies:/movies
    ports:
      - "7878:7878"
    restart: unless-stopped
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/lidarr-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/lidarr/data:/data
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/readarr-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/readarr/data:/data
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
    ports:
      - "8787:8787"
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/mylar-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/mylar/data:/data
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
    ports:
      - "8090:8090"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped


  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <pass>
    volumes:
    - CHANGE_TO_COMPOSE_DATA_PATH/postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <pass>
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3000:3000" #Server Port
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
    restart: unless-stopped
networks:
  default: 
