services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      #qbit
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/gluetun:/gluetun
      - /lib/modules:/lib/modules:ro
    environment:
     
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<KEY>
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=United States
      - SERVER_REGIONS:The Americas
      - SERVER_CITIES:Miami
      - SERVER_HOSTNAMES:us-mia.prod.surfshark.com
      - TZ=America/Detroit
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=surfshark
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Detroit
      - WEBUI_PORT=8080
    network_mode: "service:gluetun"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - CHANGE_TO_COMPOSE_DATA_PATH//qbit/config:/config
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads:/downloads
      - /srv/dev-disk-by-uuid-4559f844-1642-409b-9f46-8155bc65a232/Downloads/torrents:/torrents
    restart: unless-stopped
