---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=US/Detroit
    volumes:
      - /srv/dev-disk-by-uuid-186ca92b-dc89-4afd-8103-867b6f516c9e/Portainer/Config/heimdall/config:/config
    ports:
      - 8280:80
      - 4443:443
    restart: unless-stopped
