version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 0:0 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLEFAVOURITES: true
      ND_ENABLEREPLAYGAIN: true
      ND_ENABLESHARING: true
      ND_ENABLESTARRATING: true
      ND_PLAYLISTSPATH: "/@playlists"
      ND_ENABLEUSEREDITING: true
      ND_PROMETHEUS_ENABLED: true
      ND_PROMETHEUS_METRICSPATH: "/metrics_Navi"
      ND_AUTOIMPORTPLAYLISTS: true
      ND_LASTFM_ENABLED: true
      ND_LASTFM_LANGUAGE: "en"
      ND_LASTFM_APIKEY: "insertkey"
      ND_LASTFM_SECRET: "insertsecret"
    volumes:
      - "/srv/dev-disk-by-uuid-186ca92b-dc89-4afd-8103-867b6f516c9e/Portainer/data/Navi:/data"
      - "/srv/dev-disk-by-uuid-186ca92b-dc89-4afd-8103-867b6f516c9e/Portainer/data/Music:/music:ro"
